myfinance/MyFinance/Controllers/PlanoContaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFinance.Models;

namespace MyFinance.Controllers
{
    public class PlanoContaController : Controller
    {
        IHttpContextAccessor _httpContextAccessor;

        public PlanoContaController(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Index()
        {
            PlanoContaModel objPlanoContas = new PlanoContaModel(_httpContextAccessor);
            ViewBag.ListaPlanoContas = objPlanoContas.ListaPlanoConta();
            return View();
        }

        [HttpPost]
        public IActionResult CriarPlanoConta(PlanoContaModel form)
        {
            if (ModelState.IsValid)
            {
                form._httpContextAccessor = _httpContextAccessor;
                form.Insert();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult CriarPlanoConta(int? id)
        {
            if (id != null)
            {
                PlanoContaModel objPlanoContas = new PlanoContaModel(_httpContextAccessor);
                ViewBag.Registro = objPlanoContas.CarregarRegistro(id);
                
            }
            return View();
        }

        [HttpGet]
        public IActionResult ExcluirPlanoConta(int id)
        {
            PlanoContaModel objConta = new PlanoContaModel(_httpContextAccessor);
            objConta.Excluir(id);
            return RedirectToAction("Index");
        }


    }
}

myfinance/MyFinance/Views/PlanoConta/CriarPlanoConta.cshtml
@model PlanoContaModel
@{
    ViewData["Title"] = "Criar Plano de Conta";
}

<h3>Criar Plano de Conta</h3>

@{
    var vDescricao = "";
    var vTipo = "";
    var vId = 0;

    try
    {

        vId = int.Parse(@ViewBag.Registro.Id.ToString());
        vTipo = @ViewBag.Registro.Tipo.ToString();
        vDescricao = @ViewBag.Registro.Descricao.ToString();
    }
    catch{}
}

<form asp-controller="PlanoConta" asp-action="CriarPlanoConta" method="post">
    <input type="hidden" asp-for="Id" value="@vId" />
    <div class="form-group">
        <label for="Descricao">Descrição:</label>
        <input type="text" class="form-control" asp-for="Descricao" value="@vDescricao" />
        <span asp-validation-for="Descricao" class="text-danger"></span>
    </div>
    <div class="form-group">

        <label for="Tipo">Tipo:</label>


        @{
        if(vTipo == "R")
        {
            <div class="radio"><label><input type="radio" asp-for="Tipo" value="R" checked>Receita</label></div>
            <div class="radio"><label><input type="radio" asp-for="Tipo" value="D" unchecked>Despesa</label></div>
        }
        else
        {
            <div class="radio"><label><input type="radio" asp-for="Tipo" value="R" unchecked>Receita</label></div>
            <div class="radio"><label><input type="radio" asp-for="Tipo" value="D" checked>Despesa</label></div>
        }

        }

    </div>



    <button type="submit" class="btn btn-block btn-success">Registrar</button>
</form>

myfinance/MyFinance/Views/PlanoConta/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h3>Plano de contas</h3>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>#</th>
            <th>ID</th>
            <th>Descricao</th>
            <th>Tipo</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in (List<PlanoContaModel>)ViewBag.ListaPlanoContas)
            {

        <tr>
            <td><button type="button" class="btn btn-primary" onclick="Editar('@item.Id.ToString()')">Editar</button></td>
            <td><button type="button" class="btn btn-danger" onclick="Excluir('@item.Id.ToString()')">Excluir</button></td>
            <td>@item.Id.ToString()</td>
            <td>@item.Descricao.ToString()</td>
            <td>@item.Tipo.ToString().Replace("R", "Receita").Replace("D", "Despesa")</td>
        </tr>

            }
        }
    </tbody>
</table>

<button type="button" class="btn btn-block btn-primary" onclick="CriarPlanoConta()">Criar Plano de Conta</button>
<script>
    function CriarPlanoConta() {
        window.location.href = "..\\PlanoConta\\CriarPlanoConta";
    }

    function Excluir(id_Conta) {
        window.location.href = "..\\PlanoConta\\ExcluirPlanoConta\\"+id_Conta;
    }

    function Editar(id_Conta) {
        window.location.href = "..\\PlanoConta\\CriarPlanoConta\\" + id_Conta;
    }
</script>