myfinance/MyFinance/Controllers/ContaController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Http;
using Microsoft.AspNetCore.Mvc;
using MyFinance.Models;

namespace MyFinance.Controllers
{
    public class ContaController : Controller
    {
        IHttpContextAccessor _httpContextAccessor;

        public ContaController(IHttpContextAccessor httpContextAccessor)
        {
            _httpContextAccessor = httpContextAccessor;
        }
        public IActionResult Index()
        {
            ContaModel objConta = new ContaModel(_httpContextAccessor);
            ViewBag.ListaConta = objConta.ListaConta();
            return View();
        }
        [HttpPost]
        public IActionResult CriarConta(ContaModel form)
        {
            if(ModelState.IsValid)
            {
                form._httpContextAccessor = _httpContextAccessor;
                form.Insert();
                return RedirectToAction("Index");
            }
            return View();
        }

        [HttpGet]
        public IActionResult CriarConta()
        {
            return View();
        }

        [HttpGet]
        public IActionResult ExcluirConta(int id)
        {
            ContaModel objConta = new ContaModel(_httpContextAccessor);
            objConta.Excluir(id);
            return RedirectToAction("Index");
        }
    }
}

myfinance/MyFinance/Views/Conta/CriarConta.cshtml
@model ContaModel
@{
    ViewData["Title"] = "CriarConta";
}

<h3>CriarConta</h3>

<form asp-controller="Conta" asp-action="CriarConta" method="post">
    <div class="form-group">
        <label for="Nome">Nome:</label>
        <input type="text" class="form-control" asp-for="Nome" />
        <span asp-validation-for="Nome" class="text-danger"></span>
    </div>
    <div class="form-group">
        <label for="Saldo">Saldo:</label>
        <input type="text" class="form-control" asp-for="Saldo">
        <span asp-validation-for="Saldo" class="text-danger"></span>
    </div>



    <button type="submit" class="btn btn-block btn-success">Registrar</button>
</form>

myfinance/MyFinance/Views/Conta/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h3>Minhas contas</h3>

<table class="table table-bordered">
    <thead>
        <tr>
            <th>#</th>
            <th>#</th>
            <th>ID</th>
            <th>Nome</th>
            <th>Saldo</th>
        </tr>
    </thead>
    <tbody>
        @{
            foreach (var item in (List<ContaModel>)ViewBag.ListaConta)
            {

        <tr>
            <td><button type="button" class="btn btn-primary" onclick="Excluir('@item.Id.ToString()')">Editar</button></td>
            <td><button type="button" class="btn btn-danger" onclick="Excluir('@item.Id.ToString()')">Excluir</button></td>
            <td>@item.Id.ToString()</td>
            <td>@item.Nome</td>
            <td>R$ @item.Saldo</td>
        </tr>

            }
        }
    </tbody>
    </table>

<button type="button" class="btn btn-block btn-primary" onclick="CriarConta()">Criar Conta</button>
<script>
    function CriarConta() {
        window.location.href = "..\\Conta\\CriarConta";
    }

    function Excluir(id_Conta) {
        window.location.href = "..\\Conta\\ExcluirConta\\"+id_Conta;
    }
</script>